export const quotes = [
  "In a dream you saw a way to survive and you were full of joy.",
  "It is in your self-interest to find a way to be very tender.",
  "Turn soft and lovely anytime you have the chance.",
  "If you behaved nicely, the communists wouldn't exist.",
  "SPIT ALL OVER SOMEONE WITH A MOUTHFUL OF MILK IF YOU WANT TO FIND OUT SOMETHING ABOUT THEIR PERSONALITY FAST.",
  "Destroy superabundance. Starve the flesh, shave the hair, clarify the mind, define the will, restrain the senses, leave the family, flee the church, kill the vermin,vomit the heart, forget the dead. Limit time, forgo amusement, deny nature, reject acquaintances, discard objects, forget truths, dissect myth, stop motion, block impulse, choke sobs, swallow chatter. Scorn joy, scorn touch, scorn tragedy, scorn liberty, scorn constancy, scorn hope, scorn exaltation, scorn reproduction, scorn variety, scorn embellishment, scorn release, scorn rest, scorn sweetness, scorn light. It's a question of form as much as function. It is a matter of revulsion.",
  "You are a victim of the rules you live by.",
  "Ruin your fucking self before they do. Otherwise they'll screw you because you're a nobody. They'll keep you alive but you'll have to crawl and say \"thank-you\" for every bone they throw. You might as well stay drunk or shoot junk and be a crazy fucker. If the rich guys want to play with you, make them get their hands dirty. Send them away gagging, or sobbing if they're soft-hearted. You'll be left alone if you're frightening, and dead you're free!",
  "Savor kindness because cruelty is always possible later.",
  "You confuse me with something that is in you. I will not predict how you want to use me.",
  "I WALK IN / I SEE YOU / I WATCH YOU / I SCAN YOU / I WAIT FOR YOU / I TICKLE YOU / I TEASE YOU / I SEARCH YOU / I BREATHE YOU / I TALK / I SMILE / I TOUCH YOUR HAIR / YOU ARE THE ONE / YOU ARE THE ONE WHO DID THIS TO ME / YOU ARE MY OWN / I SHOW YOU / I FEEL YOU / I ASK YOU / I DON’T ASK / I DON’T WAIT / I WON’T ASK YOU / I CAN’T TELL YOU / I LIE / I AM CRYING HARD / THERE WAS BLOOD / NO ONE TOLD ME / NO ONE KNEW / MY MOTHER KNOWS / I FORGET YOUR NAME / I DON’T THINK / I BURY MY HEAD / I BURY YOUR HEAD / I BURY YOU / MY FEVER / MY SKIN / I CANNOT BREATHE / I CANNOT EAT / I CANNOT WALK / I AM LOSING TIME / I AM LOSING TIME / I AM LOSING GROUND / I CANNOT STAND IT / I CRY / I CRY OUT / I BITE / I BITE YOUR LIP / I BREATHE YOUR BREATH / I PULSE / I PRAY / I PRAY ALOUD / I SMELL YOU ON MY SKIN / I SAY THE WORD / I SAY YOUR NAME / I COVER YOU / I SHELTER YOU / I RUN FROM YOU / I SLEEP BESIDE YOU / I SMELL YOU ON MY CLOTHES / I KEEP YOUR CLOTHES",
  "Protect me from what I want.",
  "SOME DAYS YOU WAKE AND\nIMMEDIATELY START TO WORRY.\nNOTHING IN PARTICULAR IS WRONG,\nIT'S JUST THE SUSPICION THAT\nFORCES ARE ALIGNING QUIETLY\nAND THERE WILL BE TROUBLE.",
  "Food won't go down when you know your mother didn't want you, never liked to feed you, always hated you in her rooms. You were wrong to clutch and swallow and move your mouth. You must not be flushed, layered in fat or ripe from meat or she will despise your sight. Your skeleton cries, \"I make no demands, I am ashamed of my needs, I am unworthy. I'm aware of those more deserving, those with prior and urgent claims to food.\" Skeleton says, \"My safety is in slightness, my pride is denial. My victory is no gluttony, no guilt.",
  "BY YOUR RESPONSE TO DANGER IT IS\nEASY TO TELL HOW YOU HAVE LIVED\nAND WHAT HAS BEEN DONE TO YOU.\nYOU SHOW WHETHER YOU WANT TO STAY ALIVE,\nWHETHER YOU THINK YOU DESERVE TO,\nAND WHETHER YOU BELIEVE\nIT'S ANY GOOD TO ACT.",
  "Boredom makes you do crazy things.",
  "THERE IS A PERIOD WHEN IT IS CLEAR\nTHAT YOU HAVE GONE WRONG\nBUT YOU CONTINUE.\nSOMETIMES THERE IS A\nLUXURIOUS AMOUNT OF TIME\nBEFORE ANYTHING BAD HAPPENS.",
  "Knowing yourself lets you understand others.",
  "Expressing anger is necessary.",
  "IT'S AN EXTRAORDINARY FEELING\nWHEN PART OF YOUR BODY ARE\nTOUCHED FOR THE FIRST TIME.\nI'M THINKING OF THE SENSATIONS\nFROM SEX AND SURGERY.",
  "Raise boys and girls the same way.",
  "How do you resign yourself to something that will never be? You stop wanting just that thing. You go numb. Or you kill the agent of desire.",
  "YOU SHOULD LIMIT THE NUMBER OF TIMES\nYOU ACT AGAINST YOUR NATURE,\nLIKE SLEEPING WITH PEOPLE YOU HATE.\nIT'S INTERESTING TO TEST YOUR CAPABILITIES FOR A WHILE\nBUT TOO MUCH WILL CAUSE DAMAGE.",
  "With all the holes in you already there's no reason to define the outside environment as alien.",
  "Going with the flow is soothing but risky.",
  "At times inactivity is preferable to mindless functioning.",
  "Alienation produces eccentrics or revolutionary.",
  "A sense of timing is the mark of a genius.",
  "Expiring for love is beautiful but stupid.",
  "I try to excite myself so I stay crazy.",
];
